---
title: Joelybear.Github.Io
timezone: UTC
collections:
  _posts:
    title: Posts
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
gems:
- jekyll-redirect-from
url: http://www.joelybear.org.uk
permalink: "/:title"
